import { Mona_Sans } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";


const MonaSans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${MonaSans.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
